# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-13 04:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='AESSLIST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=50)),
                ('env', models.CharField(max_length=50)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('status', models.BigIntegerField()),
            ],
        ),
    ]
