# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-13 07:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yunwei', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BLOG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nowtime', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=1000)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JENKINSBUILDLOG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.CharField(max_length=50)),
                ('env', models.BigIntegerField()),
                ('version', models.CharField(max_length=50)),
                ('action_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='JENKINSDEPLOYLOG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.CharField(max_length=50)),
                ('env', models.BigIntegerField()),
                ('version', models.CharField(max_length=50)),
                ('action_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MESSAGE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nowtime', models.DateTimeField(auto_now_add=True)),
                ('blogid', models.BigIntegerField()),
                ('username', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('picture', models.ImageField(upload_to='./dist/img')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='aesslist',
            name='status',
            field=models.BigIntegerField(default=0),
        ),
    ]
