# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-17 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yunwei', '0002_auto_20180213_0748'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BLOG',
        ),
        migrations.DeleteModel(
            name='JENKINSBUILDLOG',
        ),
        migrations.DeleteModel(
            name='JENKINSDEPLOYLOG',
        ),
        migrations.DeleteModel(
            name='MESSAGE',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
